name: 'Deploy'

on:
  pull_request:

permissions:
  actions: write
  pull-requests: write

jobs:
  deploy_infra:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./infra/terraform/aws/application
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set environment
        id: set_env
        run: |
          if [[ "${{ github.base_ref }}" == "devel" ]]; then
              ENVIRONMENT="dev"
          elif [[ "${{ github.base_ref }}" == "stage" ]]; then
              ENVIRONMENT="stage"
          elif [[ "${{ github.base_ref }}" == "prod" ]]; then
              ENVIRONMENT="prod"
          fi

          echo "environment=$ENVIRONMENT" >> $GITHUB_OUTPUT

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
    
      - name: Check Terraform Version
        run: terraform --version

      - name: Terraform Format
        run: terraform fmt -check --recursive
      
      - name: Configure AWS-BACKEND Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Terraform init
        run: terraform init

      - name: Terraform plan
        run: TF_VAR_environment="${{ steps.set_env.outputs.environment }}" terraform plan

      - name: Terraform apply
        run: TF_VAR_environment="${{ steps.set_env.outputs.environment }}" terraform apply -auto-approve

  deploy_app:
    runs-on: ubuntu-latest
    needs: [deploy_infra]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Configure AWS-BACKEND Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Set environment
        id: set_env
        run: |
          if [[ "${{ github.base_ref }}" == "devel" ]]; then
              ENVIRONMENT="dev"
          elif [[ "${{ github.base_ref }}" == "stage" ]]; then
              ENVIRONMENT="stage"
          elif [[ "${{ github.base_ref }}" == "prod" ]]; then
              ENVIRONMENT="prod"
          fi

          echo "environment=$ENVIRONMENT" >> $GITHUB_OUTPUT

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 15.0.1
        
      - name: Install dependencies
        run: npm install
      
      - name: Build
        run: npm build && ls -ltrh
      
      - name: Deploy to s3
        run: aws s3 cp ./build/ s3://${{ steps.set_env.outputs.environment }}-lab-site-cgomez
