name: 'Deploy'

on:
  pull_request:

jobs:
  deploy_infra:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
    
      - name: Check Terraform Version
        run: terraform --version

      - name: Terraform Format
        run: terraform fmt -check --recursive
      
      - name: Configure AWS-BACKEND Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Terraform plan
        working-directory: ./infra/terraform/aws/application
        run: TF_VAR_environment="dev" terraform plan