name: 'Check branch'

on:
  pull_request:

jobs:
  check_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch
        if: (github.base_ref == 'prod' && github.head_ref != 'stage') || (github.base_ref == 'stage' && github.head_ref != 'devel')
        run: |
          echo "ERROR: You can only merge to prod from stage or from devel to stage."
          exit 1